spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: password
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 9000